name: upsetjs-jupyter-widget
channels:
  - conda-forge
dependencies:
  - r-base=3.6
  - r-tidyverse
  - r-shiny
  - r-rmarkdown
  - r-devtools
  - python
  - numpy
  - pandas
  - pip
  - pip:
      - upsetjs_jupyter_widget